/* eslint-disable perfectionist/sort-objects */
import { UnauthorizedError } from '../errors';
import { z } from 'zod'; // Import Zod

// Define the Zod schema for a single quiz question
const QuizQuestionSchema = z.object({
  question: z.string().min(1),
  options: z.array(z.string()).length(4), // Ensure exactly 4 options
  correctAnswer: z.number().int().min(0).max(3), // Index of the correct answer (0, 1, 2, or 3)
});

// Define the Zod schema for the AI's full response
const QuizResponseSchema = z.object({
  title: z.string().min(1),
  description: z.string().min(1),
  questions: z.array(QuizQuestionSchema).min(1).max(10),
});

// Adjusted QuizQuestion interface to match Zod's correctAnswer type
interface QuizQuestion {
  question?: string; // Add this
  questionText: string;
  options: string[];
  correctAnswerIndex: number; // Store the index (0-3)
}

// Define the expected structure of the Quiz object
interface GeneratedQuiz {
  id: string; // This will likely be generated by the database
  title: string;
  description: string;
  questions: QuizQuestion[];
  topic: string;
  difficulty: string;
  userId: string;
  date: string; // ISO date string
  source: 'ai';
}

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent';

// Helper function to sanitize AI response by removing markdown and extracting JSON
const sanitizeAiResponse = (text: string): string => {
  // Remove markdown code blocks like ```json or ```
  text = text.replace(/```json\n?/g, '').replace(/```\n?/g, '');
  // Attempt to extract the part that looks like JSON (starts with { and ends with })
  const jsonStartIndex = text.indexOf('{');
  const jsonEndIndex = text.lastIndexOf('}');
  if (jsonStartIndex !== -1 && jsonEndIndex !== -1 && jsonEndIndex > jsonStartIndex) {
    return text.substring(jsonStartIndex, jsonEndIndex + 1);
  }
  return text; // Return original if JSON structure not found
};


export const geminiService = {
  async generateQuizFromGemini(
    topic: string,
    difficulty: string,
    numQuestions: number,
    studyNote: string
  ): Promise<GeneratedQuiz> {
    if (!GEMINI_API_KEY) {
      throw new UnauthorizedError('Gemini API key is not configured.');
    }

    // --- 1. Construct the prompt for Gemini AI with JSON output instructions ---
    const prompt = `
      You are an expert quiz generator.
      Create a quiz based on the study material provided below.

      EXACT REQUIREMENTS:
      1. Create EXACTLY ${numQuestions} multiple-choice questions.
      2. Topic: "${topic}"
      3. Difficulty: "${difficulty}"
      4. For each question, provide exactly 4 options.
      5. Provide a creative and relevant title for the quiz.
      6. Provide a concise description/summary of what the quiz covers.

      FORMAT THE OUTPUT AS VALID JSON ONLY. 
      No markdown, no explanations, no code blocks, no conversational text.

      JSON STRUCTURE:
      {
        "title": "A creative title here",
        "description": "A short summary of the quiz content",
        "questions": [
          {
            "question": "The question text here",
            "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "correctAnswer": 0 // The index (0, 1, 2, or 3) of the correct option
          }
        ]
      }

      STUDY MATERIAL:
      """
      ${studyNote}
      """
    `;

    // --- 2. Make the call to the Gemini API ---
    try {
      const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            responseMimeType: 'application/json', // Force JSON output
          },
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        console.error('Gemini API error:', errorData);
        throw new Error(`Gemini API error: ${response.status} - ${errorData.error?.message || 'Unknown error'}`);
      }

      const data = await response.json();
      const geminiText = data.candidates[0]?.content?.parts[0]?.text;

      if (!geminiText) {
        throw new Error('No text content received from Gemini API.');
      }

      // --- 3. Parse and Validate the Gemini AI response with Zod ---
      const sanitizedText = sanitizeAiResponse(geminiText);
      let parsedJson;
      try {
        parsedJson = JSON.parse(sanitizedText);
      } catch (jsonError) {
        console.error('Failed to parse AI response as JSON:', jsonError);
        throw new Error('AI response was not valid JSON.', { cause: jsonError });
      }

      const validationResult = QuizResponseSchema.safeParse(parsedJson);

      if (!validationResult.success) {
        console.error('Zod validation errors:', validationResult.error.issues);
        throw new Error('AI response format invalid according to schema.');
      }

      const { questions: validatedQuestions, title, description } = validationResult.data;

      const questions: QuizQuestion[] = validatedQuestions.map(q => ({
        questionText: q.question,
        options: q.options,
        correctAnswerIndex: q.correctAnswer,
      }));

      // --- Placeholder for actual quiz ID and database saving ---
      // For now, we'll generate a dummy ID and current date.
      const dummyId = new Date().getTime().toString(); // Replace with actual DB ID
      const currentDate = new Date().toISOString();

      return {
        id: dummyId,
        title,
        description,
        questions,
        topic: topic || 'General',
        difficulty,
        userId: 'temp_user_id', // This will be replaced by the actual authenticated user's ID in quizController
        date: currentDate,
        source: 'ai',
      };

    } catch (error) {
      console.error('Error generating quiz from Gemini:', error);
      throw new Error('Failed to generate quiz from AI: ' + (error as Error).message, { cause: error });
    }
  },
};
